Fix not liquidating wrbtc loans
DistributedCollective/Sovryn-Node pull request #26
Opened 2021-03-09 18:43 UTC by Bitcoinera

Easy solution for easy problem :+1:

2021-03-09 18:55 UTC, jamiemadrox779 requested changes
The scripts should work on test- and mainnet

2021-03-09 19:11 UTC, Bitcoinera commented
> The scripts should work on test- and mainnet

ouch! True. Thanks for reminding me I live in Testnet-Land

2021-03-09 19:26 UTC, Bitcoinera commented
> The scripts should work on test- and mainnet

Done!

2021-03-11 19:44 UTC, jamiemadrox779 approved these changes

2021-03-11 19:44 UTC, merged